[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
# [[bin]]
# name = "day1"
# path = "src/bin/day1/main.rs"

# [[bin]]
# name = "day2"
# path = "src/bin/day2/main.rs"

[[bin]]
name = "day3"
path = "src/bin/day3/main.rs"
